# My R Programming Notes - Anahita Saghafi - May 2014

## Help

For help use "?"", 
For function argument details use "args"
  
## How toa ask questiosn in forumes?

* What steps will reproduce the problem?
* What is the expected output?
* What do you see instead?
v What Operating System?

## Skills 

* Hacking Skills: 
        * Willing to fnd answers on own own, 
        * knowledge about where to find answers on your own, 
        * unintiidated by new data types or packages, 
        * unafraid to say "I don;t know the answer", polite but relentless
* Maths and Statistics Knowledge
* Traditional Research Skills
* Substansive Expertise


## Initial Steps

* Install R
* Install R Studio
* Install Git
* Setup a Github Account
* Create Github Repo
* Link to local Repo

## Git

* Install Git on Computer
* Start Git on Computer
* mkdir to make a directory
* cd to go to the created directory: NewFolder
* got init to initiate repo
* git rempte add origin https:\\github.com\yourUserName\yourNewFolder
* got clone http:\\github.com\...
* git add
* git add -A
* git commit -m "Message" (local)
* got push (push to github)
* Branches: git checkout -b branchName
* git branch
* git checkout master

## Good sources

* http://www.bioconductor.org/
* http://cran.r-project.org/

## Finding and installing R Packages ##
 
* find.package("devtools")
* install.packages("devtools")



